# Generated by Django 4.2.7 on 2025-06-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinetuningRuleQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=100, verbose_name="게임 이름")),
                ("question", models.TextField(verbose_name="질문 내용")),
                ("answer", models.TextField(verbose_name="답변 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
            ],
            options={
                "verbose_name": "파인튜닝 룰 QA",
                "verbose_name_plural": "파인튜닝 룰 QA들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GPTRuleQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=100, verbose_name="게임 이름")),
                ("question", models.TextField(verbose_name="질문 내용")),
                ("answer", models.TextField(verbose_name="답변 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
            ],
            options={
                "verbose_name": "GPT 룰 QA",
                "verbose_name_plural": "GPT 룰 QA들",
                "ordering": ["-created_at"],
            },
        ),
    ]
